name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

env:
  TF_VERSION: '1.15.4'
  BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  
jobs:
  destroy:
    name: 'Destroy Infrastructure'
    runs-on: ubuntu-latest

    steps:
      - name: Verify Confirmation
        if: github.event.inputs.confirm != 'destroy'
        run: |
          echo "Confirmation failed. You must type 'destroy' to proceed."
          exit 1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=minecraft/terraform.tfstate" \
            -backend-config="region=$AWS_REGION"

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -input=false \
            -var="minecraft_username=${{ secrets.MINECRAFT_USERNAME }}"

      # KMS Alias and CloudWatch Log Groups are sometimes left behind by Terraform
      # Manually remove with AWS CLI
      # || true handles the case where a resource doesn't exist
      - name: Cleanup Possible Remaining Resources
        run: |
          aws kms delete-alias --alias-name alias/efs/minecraft-volume || true
          aws logs delete-log-group --log-group-name /aws/ecs/minecraft-servers || true
          aws logs delete-log-group --log-group-name /aws/ecs/minecraft-vanilla/minecraft-vanilla-task || true